env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
  - go mod tidy
builds:
- main: ./cmd/chglog
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
changelog:
  filters:
    exclude:
      - Merge
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - tap:
      owner: goreleaser
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/goreleaser/chglog
    description: chglog is a changelog management library and tool
    test: |
      system "#{bin}/chglog version"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://github.com/goreleaser/chglog
    description: chglog is a changelog management library and tool
    maintainer: Dj Gilcrease <d.gilcrease@f5.com>
    license: MIT
    vendor: GoReleaser
    formats:
      - deb
      - rpm
scoop:
  bucket:
    owner: goreleaser
    name: scoop-bucket
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  license: MIT
